var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
var codeWithConsoleConfig=[{elementId:"Example-Create-Promise",consoleElement:document.getElementById("Example-Create-Promise__Console"),func:function(){var a=this,b=new Promise(function(c,e){.5<Math.random()?c():e()});b.then(function(){a.consoleElement.innerHTML="&gt; jdu b\u011bhat<br>&gt;"});b["catch"](function(){a.consoleElement.innerHTML="&gt; nejdu b\u011bhat<br>&gt;"})}},{elementId:"Example-Arguments",consoleElement:document.getElementById("Example-Arguments__Console"),func:function(){var a=
this,b=new Promise(function(c,e){var g=Math.random();.5<g?c(g):e("n\u011bco se pokazilo")});b.then(function(c){a.consoleElement.innerHTML="&gt; Promise byl spln\u011bn, hodnota: "+c+"<br>&gt;"});b["catch"](function(c){a.consoleElement.innerHTML="&gt; Promise nebyl spln\u011bn: "+c+"<br>&gt;"})}},{elementId:"Example-Chain-Then-And-Catch",consoleElement:document.getElementById("Example-Chain-Then-And-Catch__Console"),func:function(){var a=this;(new Promise(function(b,c){.5<Math.random()?b():c()})).then(function(){a.consoleElement.innerHTML=
"&gt; jdu b\u011bhat<br>&gt;"})["catch"](function(){a.consoleElement.innerHTML="&gt; nejdu b\u011bhat<br>&gt;"})}},{elementId:"Example-Chain-Promises",consoleElement:document.getElementById("Example-Chain-Promises__Console"),func:function(){var a=this,b=function(){return new Promise(function(e,g){setTimeout(function(){e()},500+1E3*Math.random())})},c="&gt; prvn\u00ed<br>";b().then(function(){a.consoleElement.innerHTML=c+"&gt;";return b()}).then(function(){c+="&gt; druh\u00fd<br>";a.consoleElement.innerHTML=
c+"&gt;";return b()}).then(function(){c+="&gt; t\u0159et\u00ed<br>";a.consoleElement.innerHTML=c+"&gt;";return b()})["catch"](function(){a.consoleElement.innerHTML="&gt; chyba<br>&gt;"})}},{elementId:"Example-Then-Both-Arguments",consoleElement:document.getElementById("Example-Then-Both-Arguments__Console"),func:function(){var a=this;(new Promise(function(b,c){.5<Math.random()?b():c()})).then(function(){a.consoleElement.innerHTML="&gt; Promise spln\u011bn<br>&gt;"},function(){a.consoleElement.innerHTML=
"&gt; Promise nebyl spln\u011bn<br>&gt;"})}},{elementId:"Example-Catch",consoleElement:document.getElementById("Example-Catch__Console"),func:function(){var a=this,b=!1,c="&gt; Promise nebyl spln\u011bn<br>";(new Promise(function(e,g){.5<Math.random()?(e(),b=!0):g()}))["catch"](function(){a.consoleElement.innerHTML=c+"&gt;"}).then(function(){b?a.consoleElement.innerHTML="&gt; Promise spln\u011bn<br>&gt;":(c+="&gt; Promise spln\u011bn<br>",a.consoleElement.innerHTML=c+"&gt;")})}},{elementId:"Example-Finally",
consoleElement:document.getElementById("Example-Finally__Console"),func:function(){var a=this,b="&gt; funkce p\u0159edan\u00e1 metod\u011b finally se zavol\u00e1 v\u017edy<br>";(new Promise(function(c,e){.5<Math.random()?c():e()})).then(function(){b="&gt; Promise spln\u011bn<br>"+b})["catch"](function(){b="&gt; Promise nebyl spln\u011bn<br>"+b})["finally"](function(){a.consoleElement.innerHTML=b+"&gt;"})}},{elementId:"Example-Method-All",consoleElement:document.getElementById("Example-Method-All__Console"),
func:function(){var a=this,b=!1,c=new Promise(function(d,f){d(10)}),e=new Promise(function(d,f){setTimeout(d,500,20)}),g=new Promise(function(d,f){.5<Math.random()?(b=!0,d(30),a.consoleElement.innerHTML="&gt; promise3 se splnil<br>&gt;"):(f(),a.consoleElement.innerHTML="&gt; promise3 se nesplnil<br>&gt;")});Promise.all([c,e,g]).then(function(d){a.consoleElement.innerHTML=b?"&gt; promise3 se splnil<br>&gt; v\u0161echny t\u0159i Promisy se splnily<br>&gt; hodnoty v\u0161ech Promis\u016f:<br>&gt; ["+
d.toString().replaceAll(",",", ")+"]<br>&gt;":"&gt; promise3 se nesplnil<br>&gt; v\u0161echny t\u0159i Promisy se splnily<br>&gt; hodnoty v\u0161ech Promis\u016f:<br>&gt; ["+d.toString().replaceAll(",",", ")+"]<br>&gt;"})}},{elementId:"Example-Method-Any",consoleElement:document.getElementById("Example-Method-Any__Console"),func:function(){var a=this,b=!1,c=new Promise(function(d,f){.5<Math.random()?(b=!0,d(10),a.consoleElement.innerHTML="&gt; promise1 se splnil<br>&gt;"):(f(),a.consoleElement.innerHTML=
"&gt; promise1 se nesplnil<br>&gt;")}),e=new Promise(function(d,f){setTimeout(d,500,20)}),g=new Promise(function(d,f){d(30)});Promise.any([c,e,g]).then(function(d){a.consoleElement.innerHTML=b?"&gt; promise1 se splnil<br>&gt; hodnota prvn\u00edho Promisu, kter\u00fd byl spln\u011bn\u00fd: "+d+"<br>&gt;":"&gt; promise1 se nesplnil<br>&gt; hodnota prvn\u00edho Promisu, kter\u00fd byl spln\u011bn\u00fd: "+d+"<br>&gt;"})["catch"](function(d){console.log(d)})}},{elementId:"Example-Method-AllSettled",consoleElement:document.getElementById("Example-Method-AllSettled__Console"),
func:function(){var a=this,b=!1,c=new Promise(function(d,f){.5<Math.random()?(b=!0,d(10),a.consoleElement.innerHTML="&gt; promise1 se splnil<br>&gt;"):(f("vygenerovan\u00e9 \u010d\u00edslo je men\u0161\u00ed nebo se rovn\u00e1 0.5"),a.consoleElement.innerHTML="&gt; promise1 se nesplnil<br>&gt;")}),e=new Promise(function(d,f){setTimeout(d,500,20)}),g=new Promise(function(d,f){d(30)});Promise.allSettled([c,e,g]).then(function(d){var f="&gt;";d=$jscomp.makeIterator(d);for(var l=d.next();!l.done;l=d.next()){var k=
l.value;l="{";var m=[],h=Object.keys(k);h=$jscomp.makeIterator(h);for(var n=h.next();!n.done;n=h.next())m.push(n.value);k=Object.values(k);for(h=0;h<k.length;h++)m[h]="string"===typeof k[h]?m[h]+(': "'+k[h]+'"'):m[h]+(": "+k[h]);for(k=0;k<m.length;k++)l+=m[k],k<m.length-1&&(l+=", ");l+="}";f+=" "+l+"<br>&gt;"}a.consoleElement.innerHTML=b?"&gt; promise1 se splnil<br>&gt; informace o jednotliv\u00fdch Promisech: <br>"+f:"&gt; promise1 se nesplnil<br>&gt; informace o jednotliv\u00fdch Promisech: <br>"+
f})}},{elementId:"Example-Method-Race",consoleElement:document.getElementById("Example-Method-Race__Console"),func:function(){var a=this,b=new Promise(function(e,g){setTimeout(e,1E3,"prvn\u00ed Promise")}),c=new Promise(function(e,g){setTimeout(e,500,"druh\u00fd Promise")});Promise.race([b,c]).then(function(e){a.consoleElement.innerHTML="&gt; "+e+"<br>&gt;"})}},{elementId:"Example-Method-Resolve",consoleElement:document.getElementById("Example-Method-Resolve__Console"),func:function(){var a=this;
Promise.resolve("spln\u011bno").then(function(b){a.consoleElement.innerHTML="&gt; "+b+"<br>&gt;"})}},{elementId:"Example-Method-Reject",consoleElement:document.getElementById("Example-Method-Reject__Console"),func:function(){var a=this;Promise.resolve("nespln\u011bno").then(function(b){a.consoleElement.innerHTML="&gt; "+b+"<br>&gt;"})}}];